#!/usr/bin/env python2.7
'''
*****************************COPYRIGHT******************************
 (C) Crown copyright Met Office. All rights reserved.
 For further details please refer to the file COPYRIGHT.txt
 which you should have received as part of this distribution.
*****************************COPYRIGHT******************************

Created on 13 January 2016

@author: Stephen Haddad
'''

import os
import subprocess

import CrayXc40Common
import OasisCommon
import XiosCommon

[SCRIPT_DIR, LIB_DIR, SCRIPT_ENV] = CrayXc40Common.setup_path_to_scripts()

class XiosBuildCraySettings(CrayXc40Common.CrayXc40CommonSettings,
                            OasisCommon.OasisCommonSettings,
                            XiosCommon.XiosCommonSettings):
    """
    Class to contain settings for running XIOS build manual script.
    """
    def __init__(self):
        CrayXc40Common.CrayXc40CommonSettings.__init__(self)
        OasisCommon.OasisCommonSettings.__init__(self)
        XiosCommon.XiosCommonSettings.__init__(self)

        self.working_dir = os.getcwd()
        self.XIOS_DO_CLEAN_BUILD = 'true'
        self.XIOS_POST_BUILD_CLEANUP = 'false'
        self.USE_OASIS = 'true'
        self.BUILD_PATH = os.path.join(self.working_dir,
                                       'install')
        self.MTOOLS = ''
        self.XIOS_NUM_CORES = '8'
        self.XIOS_EXTERNAL_REPO_URL = \
            'http://forge.ipsl.jussieu.fr/ioserver/svn/XIOS/trunk'

def main():
    """
    Main function for running XIOS build manual script.
    """
    build_settings1 = XiosBuildCraySettings()
    env_vars = SCRIPT_ENV.copy()
    env_vars.update(build_settings1.__dict__)

    exec_name1 = 'xios_build'

    cmd1 = ''
    for module_path in build_settings1.XBS_PREREQ_MODULES.split(','):
        cmd1 += 'module load {0}\n'.format(module_path)
    cmd1 += '''
module use $MODULE_INSTALL_PATH/modules
module load $OASIS3_MCT/$OASIS_MODULE_VERSION/$ROSE_SUITE_REV_NO/$OASIS_REV_NO

{EXEC}'''

    cmd1 = cmd1.format(EXEC=exec_name1)
    subprocess.call(cmd1,
                    env=env_vars,
                    shell=True)

if __name__ == '__main__':
    main()
