#!/usr/bin/env python2.7
'''
*****************************COPYRIGHT******************************
 (C) Crown copyright Met Office. All rights reserved.
 For further details please refer to the file COPYRIGHT.txt
 which you should have received as part of this distribution.
*****************************COPYRIGHT******************************
Created on 13 January 2016

@author: Stephen Haddad
'''
import os
import subprocess

import CrayXc40Common
import OasisCommon
import XiosCommon

[SCRIPT_DIR, LIB_DIR, SCRIPT_ENV] = CrayXc40Common.setup_path_to_scripts()
import XiosModuleWriter

class XiosTestCraySettings(CrayXc40Common.CrayXc40CommonSettings,
                           OasisCommon.OasisCommonSettings,
                           XiosCommon.XiosCommonSettings):
    def __init__(self):
        """
        Class to contain settings for running XIOS test manual script.
        """
        CrayXc40Common.CrayXc40CommonSettings.__init__(self)
        OasisCommon.OasisCommonSettings.__init__(self)
        XiosCommon.XiosCommonSettings.__init__(self)

        self.working_dir = os.getcwd()


def main():
    """
    Main function for running XIOS test manual script.
    """
    test_settings = XiosTestCraySettings()
    env_vars = SCRIPT_ENV.copy()
    env_vars.update(test_settings.__dict__)

    exec_name1 = 'xios_test'
    cmd1 = ''
    for module_path in test_settings.XBS_PREREQ_MODULES.split(','):
        cmd1 += 'module load {0}\n'.format(module_path)
    cmd1 += '''
module use $MODULE_INSTALL_PATH/modules
module load {XIOS_PRGENV}/{XIOS_PRGENV_MOD_VER}
{EXEC}'''
    cmd1 = cmd1.format(
        EXEC=exec_name1,
        XIOS_PRGENV=XiosModuleWriter.XiosPrgEnvWriter.XIOS_PRGENV_NAME,
        XIOS_PRGENV_MOD_VER=test_settings.XIOS_PRGENV_VERSION)
    subprocess.call(cmd1,
                    env=env_vars,
                    shell=True)

if __name__ == '__main__':
    main()
