#!/usr/bin/env python2.7
"""
Script to run all unit tests on UKMO Cray XC40 platform
"""
import unittest
import sys
import os
import datetime


# find parent directory directory containing this file so that source code
# can be imported
SCRIPT_DIR = os.path.abspath(os.path.join(os.path.realpath(__file__),
                                          os.pardir,
                                          os.pardir))
sys.path += [SCRIPT_DIR]

LIB_DIR = os.path.abspath(os.path.join(SCRIPT_DIR,
                                       'lib'))
sys.path += [LIB_DIR]

from xios_build_tests import XiosBuildCrayTests
from nemo_build_tests import NemoBuildCrayTests
from oasis_build_tests import OasisBuildCrayTests

SCRATCH_DIR_NAME = 'scratch_XBStest_'

def main():
    # setting up working directory. A directory can be passed in as argument
    # or the current directory will be used. The actual files will be put in
    # a subdirectory of the current or input directory
    if len(sys.argv) < 2:
        working_dir = os.getcwd()
    else:
        working_dir = sys.argv[1]
    date_time_str = datetime.datetime.now().strftime('%Y_%m_%d_%H_%M_%S')
    working_dir = os.path.join(working_dir,
                               SCRATCH_DIR_NAME + '_' + date_time_str)
    if not (os.path.exists(working_dir) and os.path.isdir(working_dir)):
        os.mkdir(working_dir)
    os.chdir(working_dir)
    print 'test files will be created in {testDir}'.format(testDir=os.getcwd())

    module_suites = [
        unittest.TestLoader().loadTestsFromTestCase(XiosBuildCrayTests),
        unittest.TestLoader().loadTestsFromTestCase(NemoBuildCrayTests),
        unittest.TestLoader().loadTestsFromTestCase(OasisBuildCrayTests)]
    cray_suite = unittest.TestSuite(module_suites)

    test_results = unittest.TextTestRunner(verbosity=2).run(cray_suite)
    if len(test_results.errors) > 0 or len(test_results.failures) > 0:
        exit(1)


if __name__ == '__main__':
    main()
